sudo: false
language: erlang
otp_release:
  - 21.0
before_install:
  - pip install --user codecov
script: bin/rebar3 eunit
after_success:
  - bin/covertool -cover _build/test/cover/eunit.coverdata -appname httpc_aws -output cobertura.xml
  - codecov
